GET http://localhost:3000/
###
GET http://localhost:3000/
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJoZW5yeSIsImlhdCI6MTY1MjYwMTY4MSwiZXhwIjoxNjUyNjAxNzQxfQ.I3hxawy8mBVi6ItrGjiR-TphWcnkPyczX1dPJRMe6xI
###
POST http://localhost:3000/login
Content-Type: application/json 

{
    "username": "henry"
}

###
// yeu cau token moi 
POST http://localhost:3000/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJoZW5yeSIsImlhdCI6MTY1MjYwMTcxMSwiZXhwIjoxNjUyNjA1MzExfQ.xAoniVEitlNKHRLH6Scno4hky1sPb_DMWXBw8QDE-i0"
}

###
DELETE http://localhost:3000/logout
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJoZW5yeSIsImlhdCI6MTY1MjYwMTcyNSwiZXhwIjoxNjUyNjAxNzg1fQ.38fSlu1JvBdi-3UvIlYXiOJAJ6FGNaRJ8qQqjJfbXy4